Empty opmodes
BotsBurgh/BOTSBURGH-FTC-2024-25 pull request #14
Opened 2024-05-19 21:59 UTC by ImTheBiggestBird2

Empty autonomous and teleop opmodes

2024-05-25 00:13 UTC, BD103 requested changes

2024-05-25 00:13 UTC, BD103 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/teleOp/teleOpMain.kt
Could you move this to `teamcode/teleop/TeleOpMain.kt`? (Folders are all lowercase, filenames are upper camel-case.)

Furthermore, could you add the `TeleOpMain` class? You can look at [last year's code](https://github.com/BotsBurgh/BOTSBURGH-FTC-2023-24/blob/457483751af7fa941e585ce53c3079d9ef7ac94f/TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmode/teleop/TeleOpMain.kt#L15-L17) for an example. Feel free to delete the contents of the `init` and `loop` functions, since none of the code called within them has been migrated yet.

2024-05-25 00:13 UTC, BD103 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/autonomous/autoMain.kt
Same thing as my other comment :)

Could you move this to `teamcode/autonomous/AutoMain.kt`? (Make sure it extends a `LinearOpMode`, unlike `TeleOpMain` which extends an `OpMode`.)

I'd look at [`DemoAutonomous`](https://github.com/BotsBurgh/BOTSBURGH-FTC-2023-24/blob/457483751af7fa941e585ce53c3079d9ef7ac94f/TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmode/autonomous/DemoAutonomous.kt#L10-L12) from last year instead of `AutoMain`, since `AutoMain` uses some weird inheritance shenanigans that I can explain next time we meet.

2024-05-30 23:17 UTC, BD103 approved these changes

2024-05-31 00:30 UTC, ImTheBiggestBird2 reviewed
Looks good i think!

2024-06-02 17:49 UTC, medham01 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/autonomous/AutoMain.kt
add comments when class is created,
add hardware components in initialization,
be specific + add autonomous hardware power values to make robot move

2024-06-02 17:57 UTC, medham01 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/teleOp/TeleOpMain.kt
again, make sure to initialize hardware components
implement joystick components in teleop

2024-06-02 19:31 UTC, cadenceforney approved these changes
Looks good to me.

2024-06-02 20:19 UTC, BD103 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/teleOp/TeleOpMain.kt
> +    override fun init() {}
line specific

2024-06-02 20:45 UTC, merged